### PR TITLE
Adding Cosmos DB change feed + spark demo

### PR DESCRIPTION
**Pull request by heyyjudes**
adding

### CODE REVIEW

**Comment by heyyjudes** [comment]
@dennyglee for review

**Comment by dennyglee** [comment]
@heyjudes - small request, could you re-run the notebook so there are results showing up in it?  This way when readers view the sample notebook, they can see the results cached in the notebook. Thanks!

**Comment by heyyjudes** [comment]
@dennyglee Sure! added results!

**Comment by dennyglee** [comment]
LGTM!  thanks!

**Pull request merged**
