### PR TITLE
Fixing a dependency issue causing Direct Transport over TCP to fail with RequestTimeoutException

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**

### CODE REVIEW

**Comment by rifuller** [comment]
Can you describe what the root cause is?  The dependency package versions aren't changed so excluding those files caused request timeouts?

**Review by argium — COMMENTED** [review]
Can you describe what the root cause is?  The dependency package versions aren't changed so excluding those files caused request timeouts?

**Comment by FabianMeiswinkel** [comment]
> Can you describe what the root cause is?  The dependency package versions aren't changed so excluding those files caused request timeouts?

Both changes were necessary - changing the order of dependencies changed which transient dependency version for Guava were effectively used. Including the async SDK in the list of dependencies to be shaded made sure it wouldn't result into conflicts with the versions of for example guava being provided by the hosting environment (Databricks runtime etc.)

Makes sense?

**Comment by argium** [comment]
> 
> 
> > Can you describe what the root cause is?  The dependency package versions aren't changed so excluding those files caused request timeouts?
> 
> Both changes were necessary - changing the order of dependencies changed which transient dependency version for Guava were effectively used. Including the async SDK in the list of dependencies to be shaded made sure it wouldn't result into conflicts with the versions of for example guava being provided by the hosting environment (Databricks runtime etc.)
> 
> Makes sense?

More or less!  Java never ceases to surprise me with its weirdness.  I wouldn't have thought the order dependencies are declared makes a difference but I can see when shading a JAR it has to resolve conflicts in _some_ order.

**Review by kirankumarkolli — APPROVED** [review]

**Pull request merged**
